### ISSUE TITLE
Task not appearing in list

### ISSUE THREAD

**Issue by flcdrg** [Fernfrost/vsts-task-agent-capabilities#1]
I've added Agent Capabilities to our Azure DevOps organisation, but when I go to create a new build pipeline, it isn't appearing in the list of available tasks. If I search, it does show under the Marketplace heading, but there it says 'Installed', so I don't see a way of adding it to the current build.

Any suggestions?

**Comment by Fernfrost** [comment]
Hi!

Sorry you are having trouble.

It should be visible under Utility. This is a screenshot from our own Azure DevOps just now.

![image](https://user-images.githubusercontent.com/11902905/49504605-4c9f3180-f87a-11e8-8932-1f4218a1bdba.png)

Is it listed as installed under Organization Settings -> Extensions?

Have you tried uninstalling and then reinstalling?

**Comment by flcdrg** [comment]
No.. it shows like this:

![image](https://user-images.githubusercontent.com/384747/49512321-85242700-f8dd-11e8-9852-a25938c312b3.png)

Yes, it is listed in Organization Settings / Extensions, but I might try "turning it off and on again". Weird.

**Comment by flcdrg** [comment]
And what do you know? Uninstalling/reinstalling worked. Must be a strange DevOps bug.
