### ISSUE TITLE
Alternate to requiring PAT?

### ISSUE THREAD

**Issue by flcdrg** [Fernfrost/vsts-task-agent-capabilities#2]
I noticed this code - https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/securefiles-common/securefiles-common.ts that if I read it correctly, seems to get a server connection without requiring passing in a PAT.

I wonder if that's viable for this task, or whether you already tried something like that and it wasn't suitable?

**Comment by flcdrg** [comment]
Maybe not.. it gets as far as looking for the `queue` property in the return from `getBuild` but that doesn't seem to be populated when using the system token

**Comment by Fernfrost** [comment]
Tried that but for now PAT is required to get the information.

I agree that doing without the PAT would be the better solution
