### ISSUE TITLE
Support userCapabilities

### ISSUE THREAD

**Issue by flcdrg** [Fernfrost/vsts-task-agent-capabilities#3]
Currently only systemCapabilities are copied. It would be good to support userCapabilities too

**Comment by Fernfrost** [comment]
This is a good idea and implementation looks good.

Using .System. and .User. in variable names will break functionality for existing installations so this will have to be version 2.

**Comment by flcdrg** [comment]
No worries. The other option would be to just append the user ones, which wouldn't be breaking

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Fernfrost** [comment]
Published version 1.0.5 that has support for both system and user capabilities.
Legacy variable naming kept for backward compatibility. 

Please try it out and report back.
